fix: change navbar dropdown icon to InitialIcon
virtool/virtool-ui pull request #105
Opened 2022-05-10 19:55 UTC by elanjm12

Change navbar dropdown icon to InitialIcon. Add text description of which user is logged in.

![Screenshot from 2022-05-10 12-52-52](https://user-images.githubusercontent.com/97321944/167710991-d05798ab-0f4b-4c50-aaef-4e50cc0e3068.png)

2022-05-10 22:11 UTC, ReeceHoffmann requested changes
Overall I think the visual aspects of the PR look good. (though Ian's opinion is what really matters) As a general comment you should always take a look at what changes deep source is suggesting. For this PR deep source is highlighting a couple of issues that should be addressed. (redundant imports and should use self closing tag for `initialIcon`)

Anyway, I also left some specific feedback on parts of the code I would change. Ian might disagree on the visual style notes, so I wouldn't blame you for waiting to implement those. Otherwise you should be safe to implement everything else.

2022-05-10 22:11 UTC, ReeceHoffmann commented on src/js/nav/components/NavBar.js
> +import React, { useMemo } from "react";
Remove useMemo

2022-05-10 22:11 UTC, ReeceHoffmann commented on src/js/nav/components/NavBar.js
> +                    <InitialIcon handle={handle} size="md"></InitialIcon>
```suggestion
                    <InitialIcon handle={handle} size="md"/>
```

2022-05-10 22:11 UTC, ReeceHoffmann commented on src/js/nav/components/NavBar.js
> +                        Signed in as <b>{handle}</b>
```suggestion
                        Signed in as <strong>{handle}</strong>
```

Both should act identically in standard browsers, but can behave differently with assistive technology and non-standard browsers as `<b>` is strictly styling while `<strong>` indicates semantic importance

2022-05-10 22:11 UTC, ReeceHoffmann commented on src/js/nav/components/NavBar.js
> +                    <DropdownMenuLink to="/account">
I think having the username act like a link to account is a good idea, but I am personally not a huge fan of how `<DropdownMenuLink>` will lightly shade the background when hovered for this exact case. You might be able to override this behavior by restyling it via styled components, or implement the link another way. (Also possible Ian will disagree with me on the shading)

2022-05-10 22:11 UTC, ReeceHoffmann commented on src/js/nav/components/NavBar.js
> +    handle: state.account.handle
When available, I try to use selectors to get data from redux state as they should be updated if the format of the redux state is ever changed. In this case there is the `getAccountHandle` selector from `account/selectors.js` I would use.

2022-05-11 18:39 UTC, igboyes requested changes
Two things:

1. Extend thick grey bar to entire width of dropdown.
2. Commit message needs to change.
    This will appear in release notes and `InitialIcon` has no meaning to a user.
    How about: _fix: use user profile image for account drop down_

2022-05-16 20:52 UTC, igboyes approved these changes

2022-05-16 20:52 UTC, merged