fix: skull icon display for terminated jobs
virtool/virtool-ui pull request #106
Opened 2022-05-10 21:31 UTC by elanjm12

Skull icon is displayed for terminated jobs. 

![Screenshot from 2022-05-10 14-26-22](https://user-images.githubusercontent.com/97321944/167724610-a4693db4-8d8b-41b6-b698-31426859aaee.png)

2022-05-10 22:44 UTC, ReeceHoffmann requested changes
From the zoomed in view it looks good to me. Few small changes to the code below.

2022-05-10 22:44 UTC, ReeceHoffmann commented on src/js/jobs/components/Item/Status.js
> +                <Icon name="fa-solid fa-skull" color="red" />
```suggestion
                <Icon name="skull fa-fw" color="red" />
```

The `Icon` base component should only need `name="skull"` to get the correct icon. (`fa-fw` specifies that the icon needs to have a fixed width)

2022-05-10 22:44 UTC, ReeceHoffmann commented on src/js/jobs/components/Item/Status.js
> +    }
```suggestion
        if (state === "complete") {
            return (
                <StyledJobStatus pad={pad}>
                    <Icon name="check fa-fw" color="green" />
                    <span>{state}</span>
                </StyledJobStatus>
            );
        }
```
Remove extra brackets

2022-05-11 18:26 UTC, igboyes requested changes
The only difference between the two big `if` blocks is the `Icon.name`.

```js
<Icon name={`fa-fw ${"skull" ? state === "terminated" : "times"}`} color="red" />
```
* [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)
* [Ternary Operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator)

2022-05-11 19:26 UTC, ReeceHoffmann commented
To add onto Ian's comment, I think using a ternary operator instead of a separate if statement here is a good idea. Though looking at how similar many of the states are in structure, (only changing the icon name and color) it might be a good idea to see if there is a way to simplify/optimize the code further by taking advantage of these similarities.

2022-05-11 20:35 UTC, igboyes approved these changes

2022-05-11 21:27 UTC, merged