fix: label description renders below label component
virtool/virtool-ui pull request #107
Opened 2022-05-11 17:00 UTC by elanjm12

Label descriptions render below the label component.

![Screenshot from 2022-05-11 09-49-43](https://user-images.githubusercontent.com/97321944/167905979-de5899ea-5cbe-46c5-a9a0-037a3a88e4e0.png)

2022-05-11 23:32 UTC, ReeceHoffmann requested changes
While this gets the job done I think a few style tweaks would be nice. 

For the description I would
1. Change the font size to `sm` 
2. Change the color to `greyDarkest`
3. Consider offsetting the description 5px to the right to have it align with the start of the label contents rather than the border of the label

Updated image:
![image](https://user-images.githubusercontent.com/59776400/167963190-d43a68c3-86cf-412a-a575-01e3e12a2733.png)

For all the font sizes and colors you will want to get them from the theme component in `src/app/theme.js`. For styling use the library styled-components and take a look at other components for examples of how to leverage `theme` while styling other components. Feel free to experiment with other ideas as well, I am by no means attached to this specific style.

2022-05-11 23:53 UTC, igboyes requested changes

2022-05-11 23:53 UTC, igboyes commented on src/js/samples/components/Sidebar/Labels.js
> +    <p>
A `div` is more semantic here and should accomplish the same effect because it is also a block-level element.

Use `p` for blocks of text.

2022-05-11 23:55 UTC, igboyes commented
> Consider offsetting the description 5px to the right to have it align with the start of the label contents rather than the border of the label.

Keep as is. Other points are fine.

2022-05-12 19:00 UTC, elanjm12 commented
Updated screenshot of labels ui.

![Screenshot from 2022-05-12 11-56-49](https://user-images.githubusercontent.com/97321944/168148983-7a284b23-4935-4635-8d24-4aef23865cea.png)

2022-05-12 21:44 UTC, igboyes approved these changes

2022-05-12 21:45 UTC, merged