fix: add overflow handling to label chooser in create sample view to prevent overflow
virtool/virtool-ui pull request #110
Opened 2022-05-13 17:31 UTC by elanjm12

Overflow handling added to label chooser in create sample view

![Screenshot from 2022-05-13 10-30-34](https://user-images.githubusercontent.com/97321944/168336968-e9584acf-1818-4902-874c-f4b59f39390d.png)
.

2022-05-13 17:48 UTC, igboyes requested changes
Can you tweak this so the filter input component stays visible at the top and only the label list scrolls?

2022-05-15 23:01 UTC, elanjm12 commented
filter input component remains visible while scrolling 

![Screenshot from 2022-05-15 15-59-49](https://user-images.githubusercontent.com/97321944/168497621-d26a90ae-c7d1-442a-b2f6-b97ac45c51be.png)

2022-05-16 19:46 UTC, igboyes requested changes
Please also change commit message to something a user will understand (eg. _prevent excessive label selector menu heights_).

2022-05-16 19:46 UTC, igboyes commented on src/js/samples/components/Sidebar/Selector.js
> +                    <StyledDiv>
`StyledLinkButton` is incorrectly named, so don't follow that as an example.

The Styled Components convention is to use the `Styled` prefix only in the following situation:
```js
const StyledBar = styled.div`...`;

const Bar = props => (
  <StyledBar>
    ...
  </StyledBar>
);
```

https://styled-components.com/docs/basics#how-do-styled-components-work-within-a-component

---

Can you rename `StyledLinkButton` to `SampleSidebarSelectorButton`?

2022-05-18 19:56 UTC, igboyes approved these changes

2022-05-18 19:56 UTC, merged