fix: make filtering feature work on single character input and add tests
virtool/virtool-ui pull request #124
Opened 2022-05-27 16:40 UTC by elanjm12

Usefuse returns results on single character inputs. And tests added for useFuse hook.

![Screenshot from 2022-05-27 09-05-43](https://user-images.githubusercontent.com/97321944/170736979-47858917-58dc-4cee-b23f-96babb11e949.png)

2022-05-27 20:02 UTC, ReeceHoffmann requested changes
Tests mostly look good couple of comments though:

1. Not directly test related, but my understanding was that we wanted to ensure the `useFuse` always returned an object of consistent structure. Not sure that goal changed in your talks with Ian, but right now the `collection` object and the object returned when there is a search term have a  different structure.

2. I mentioned this on slack, but for readability reasons I would suggest reformatting the test names to match the "should <action> when <action prompt>" format that is standard in the codebase

2022-05-27 20:02 UTC, ReeceHoffmann commented on src/js/base/__tests__/UseFuse.test.js
> +        expect(result.current[0]).toBe(collection);
Since returning collection is currently the default state, I would personally separate the two calls to `setTerm` and confirm that collection is not being returned when a term is set. That way we can be fully confident that collection is being returned is really the result of reversion to returning collection rather than just always having returned collection.

2022-05-27 20:02 UTC, ReeceHoffmann commented on src/js/base/__tests__/UseFuse.test.js
> +        const [ returnObj, term, setTerm] = result.current;
In cases like this where the restructured values for `returnObj` and `term` can't be used, I would just pull out the one term that is used.

2022-05-30 23:19 UTC, igboyes requested changes
Change `UseFuse.test.js` to `hooks.test.js` and I will merge.

2022-05-31 18:17 UTC, igboyes approved these changes

2022-05-31 18:18 UTC, merged