Elanjm2/vir 1548 use vitest in ci
virtool/virtool-ui pull request #171
Opened 2022-09-08 20:38 UTC by elanjm12

2022-09-08 23:02 UTC, elanjm12 commented
Ready for review.

Test files switched to have .jsx ending.
Tests converted where needed to be compatible with vitest.
jest.fn() => vi.fn()
github actions updated

2022-09-08 23:10 UTC, igboyes requested changes
What does this mean: `ShallowWrapper {}`? Are you sure our snapshot are still intact?

2022-09-08 23:10 UTC, igboyes commented on .vscode/extensions.json
> +{
Remove your `.vscode` directory from the PR. Add the folder to `.gitignore`.

2022-09-13 19:26 UTC, igboyes requested changes

2022-09-13 19:26 UTC, igboyes commented on package.json
> +    "@vue/test-utils": "^2.0.2",
Should be dev dependencies.

2022-09-14 15:54 UTC, merged