chore: add storybook
virtool/virtool-ui pull request #173
Opened 2022-10-03 14:23 UTC by elanjm12

2022-10-04 23:32 UTC, igboyes requested changes

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/Button.stories.js
> +};
I am not sure what the point of these is.

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/LinkButton.stories.js
> +    to: "/",
This should keep us at the same path instead of going back to root.
```suggestion
    to: "#",
```

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/LinkButton.stories.js
> +    children: "this is a green link button"
```suggestion
    children: "Link Button"
```

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/LinkButton.stories.js
> +};
This would be terrible design so let's just remove it. Not worth considering.

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/NoneFound.stories.js
> +};
```suggestion
```

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/NoneFoundBox.stories.js
> +    noun: "hello"
```suggestion
    noun: "items"
```

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/NoneFoundBox.stories.js
> +};
Why?

2022-10-04 23:32 UTC, igboyes commented on src/js/base/stories/NoneFoundBox.stories.js
> +};
Remove unless you have a justification. This would not ever be implemented in reality.
```suggestion
```

2022-10-12 14:40 UTC, elanjm12 commented on src/js/base/stories/Button.stories.js
> +};
I was more just playing around and getting used to using storybook in this case. But its been removed now.

2022-10-12 19:19 UTC, igboyes approved these changes

2022-10-12 19:20 UTC, merged