feat: add pagination base component
virtool/virtool-ui pull request #187
Opened 2022-11-08 18:20 UTC by elanjm12

![Screenshot from 2022-11-08 10-19-27](https://user-images.githubusercontent.com/97321944/200644278-cc170f5c-570d-41e2-8ede-f301de8e31f4.png)

2022-11-10 21:47 UTC, igboyes requested changes
For all paging endpoints we get the following:
```
{
  "found_count": 1022,
  "page": 1,
  "page_count": 41,
  "per_page": 25,
  "total_count": 1026
}
```
Keep this in mind when working on this component.

Think about where values used in your component come from. Do they belong in component state or is their authoritative source somewhere else?

2022-11-10 21:47 UTC, igboyes commented on src/js/base/Pagination.jsx
> +export const Pagination = ({ itemsPerPage, totalItems, color }) => {
Drop `color` prop. Pagination components are not going to vary in appearance over the application UI.

2022-11-10 21:47 UTC, igboyes commented on src/js/base/Pagination.jsx
> +    return pageNumbers.slice(currentPage - 2, currentPage + 2);
Good use of `min()`, `max()`, and `range()` can greatly simplify this function.

If you are returning in `if` blocks, don't bother with `else if`. This is functionally equivalent:
```js
    if (pageNumbers.length <= 4) {
        return pageNumbers;
    } 

    if (currentPage === 1) {
        return pageNumbers.slice(0, 4);
    }

    if (currentPage === pageNumbers.length) {
        return pageNumbers.slice(pageNumbers.length - 4, pageNumbers.length);
    }

    ...        
```

2022-11-10 21:47 UTC, igboyes commented on src/js/base/Pagination.jsx
> +export const sliceData = (items, currentPage, itemsPerPage) => {
Are you sure this is used somewhere?

2022-11-10 21:47 UTC, igboyes commented on src/js/base/Pagination.jsx
> +    const pageNumbers = range(1, Math.ceil(totalItems / itemsPerPage + 1));
Are you sure defining this array is the most efficient and clear way to implement this?

2022-11-10 21:47 UTC, igboyes commented on src/js/base/Pagination.jsx
> +        <StyledPaginationBox size={pageNumbers.length}>
What is `size` used for?

2022-11-16 23:41 UTC, igboyes requested changes
Fix the bool issues and I will merge.

When we use this component, I think we are going to be forced to change it a bit. The pagination should work via URLs (eg. `?page=2`), no these page numbers and buttons will have to be links instead of having `onClick` handlers.

At that point, I'd like all of the clickable elements, except for **Next** to be styled as basic links. Next will be the most commonly clicked and should have the most visual weight.

2022-11-16 23:41 UTC, igboyes commented on src/js/base/Pagination.jsx
> +            active={currentPage === pageNumber ? true : false}
```suggestion
            active={currentPage === pageNumber}
```

2022-11-16 23:41 UTC, igboyes commented on src/js/base/Pagination.jsx
> +                disabled={currentPage === 1 ? true : false}
```suggestion
                disabled={currentPage === 1}
```

2022-11-16 23:41 UTC, igboyes commented on src/js/base/Pagination.jsx
> +                {"Next >"}
```suggestion
                Next
```

2022-11-17 14:15 UTC, elanjm12 commented
bool issues addressed. I will address the first comment when I use this component in issue 1623.

2022-11-17 15:56 UTC, igboyes approved these changes

2022-11-17 15:57 UTC, merged