chore: add user classes, fake data, user tests remove enzyme
virtool/virtool-ui pull request #194
Opened 2022-12-08 21:05 UTC by elanjm12

Remove enzyme from all user tests. Replace with rtl. Add user classes in typescript and use faker js to populate fake data.

2022-12-08 22:24 UTC, igboyes requested changes
Thanks for getting this process started.

Please make these tests more readable by:
1. Introducing logical whitespace.
    * Put prep, events, and assertion in separate blocks. Examples provided.
    * If you do mulitple rounds and events and assertions, split them up with whitespace.
2. Removing unnecessary variables that are only used once.

DRY-ify your unnecessarily repetitious `createAppStore()` function and associated setup. This looks like it has essentially been copy-pasted between test modules.

Use `userEvent` wherever possible instead of `fireEvent`. Google for benefits of `user-events`.

You have added functions with prefixes `getFakeDocuments`. The `get` prefix implies you are getting a property from an object. Use `create` instead.

2022-12-08 22:24 UTC, igboyes commented on src/js/users/components/__tests__/Create.test.jsx
> +        expect(props.onCreate).not.toHaveBeenCalled();
Example of making test more readable.
```suggestion
        renderWithRouter(<CreateUser {...props} />, state, history);
        
        userEvent.click(screen.getByRole("button", { name: "Save" }));
        
        expect(screen.getByText("Please specify a username")).toBeInTheDocument();
        expect(screen.getByText("Passwords must contain at least 8 characters")).toBeInTheDocument();
        expect(props.onCreate).not.toHaveBeenCalled();
```

2022-12-08 22:24 UTC, igboyes commented on src/js/users/components/__tests__/Create.test.jsx
> +        expect(props.onCreate).toHaveBeenCalled();
Example of making test more readable.

```suggestion
        renderWithRouter(<CreateUser {...props} />, state, history);
        
        fireEvent.change(screen.getByLabelText("username"), { target: { value: "newUsername" } });
        fireEvent.change(screen.getByLabelText("password"), { target: { value: "newPassword" } });
        
        expect(props.onCreate).not.toHaveBeenCalled();
        
        screen.getByRole("button", { name: "Save" }).click();
        
        expect(props.onCreate).toHaveBeenCalled();
```

2022-12-08 22:24 UTC, igboyes commented on src/js/users/classes.ts
> +    );
Based on the Lodash docs, this should work.
```suggestion
    const groups = times(5, (i: number) => ({
        id: faker.random.alphaNumeric(9, { casing: "lower" }),
        name: `group${i}`,
        toggled: true
    }));
```

2022-12-13 22:35 UTC, ReeceHoffmann submitted a review, later dismissed

2022-12-13 23:00 UTC, igboyes approved these changes, later dismissed

2022-12-14 00:01 UTC, merged