Add administrator managment view
virtool/virtool-ui pull request #222
Opened 2023-05-04 22:47 UTC by ReeceHoffmann

Changes:
- update UI to use `administrator_role` in place of legacy `administrator`
- add administrator management tab to admin view
- add complete data models for user(s), account, groups, and permissions. Includes all supporting models
- add complete fake data generation of user(s), account, groups, and permissions
- add `GET` api route mocking for `/account`, `/admin/roles`, `/admin/users`, and 
- add api `PUT` route mocking for `admin/users/{user_id}/role` 
- update tests as required

2023-05-31 17:23 UTC, igboyes requested changes
Please change combox files names like `SearchBar` -> `ComboBoxSearchBar`. This is a convention we have not been following.

This works well. I'm going to merge and make changes to style later if that's okay with you. There are a few minor accessibility issues and edge cases I will make issues for.

2023-05-31 17:23 UTC, igboyes commented on src/js/administration/components/administrators/Administrators.tsx
> +                <InputSearch name="search" aria-label="search" value={term} onChange={onSearch} />
What is the point of this?

2023-05-31 17:23 UTC, igboyes commented on src/js/administration/components/administrators/Item.tsx
> +            <Icon name="trash" color="red" onClick={() => onChange(null)} aria-label="remove role" />
```suggestion
            <Icon name="trash" color="red" onClick={() => onChange(null)} aria-label="Remove administrator role" />
```

2023-05-31 17:23 UTC, igboyes commented on src/js/base/select/SelectButton.tsx
> +import { Trigger, Value } from "@radix-ui/react-select";
I prefer that this is unchanged. It makes our code match the examples in the docs and makes it obvious what Radix component `Trigger` and `Value` are associated with.

2023-05-31 17:23 UTC, igboyes commented on src/js/samples/components/Detail/Rights.jsx
> +                            <InputLabel>{"All Users' Rights"}</InputLabel>
Why was this necessary?

2023-05-31 17:23 UTC, igboyes commented on src/js/utils/reducers.js
> +    });
Restructure so condition is `if (list) {}`.

2023-06-01 16:57 UTC, ReeceHoffmann commented on src/js/samples/components/Detail/Rights.jsx
> +                            <InputLabel>{"All Users' Rights"}</InputLabel>
it isn't... reverted

2023-06-02 17:18 UTC, igboyes commented
Resolve conflicts on this @ReeceHoffmann and I will merge.

2023-06-02 18:28 UTC, igboyes approved these changes

2023-06-02 18:33 UTC, merged