Rastinrashidi/UI 54 use react query for creating the first user
virtool/virtool-ui pull request #266
Opened 2023-09-26 22:23 UTC by raastinn

2023-09-29 15:34 UTC, ReeceHoffmann reviewed
See if you can use the built in error handling from `useMutation`, otherwise this looks good to me!

2023-09-29 15:34 UTC, ReeceHoffmann commented on src/js/wall/FirstUser.jsx
> +    const [error, setError] = useState("");
Why not use the error handling baked into useMutation? https://tanstack.com/query/v4/docs/react/guides/mutations

2023-09-29 15:58 UTC, ReeceHoffmann commented on src/js/wall/FirstUser.jsx
> +export default function FirstUser() {
Please add a docstring for `FirstUser`

2023-10-03 18:37 UTC, igboyes requested changes

2023-10-03 18:37 UTC, igboyes commented on src/js/wall/FirstUser.jsx
> + * Responsible for creating the first Virtool user
Think of component docstrings like you are telling another developer what they will get from it.
```suggestion
 * A form for creating the first instance user.
```
Take a look at these docs for examples like:
* A vertically stacked set of interactive headings that each reveal a section of content.
* A date field component that allows users to enter and edit date.
* A control that allows the user to toggle between checked and not checked.

2023-10-06 19:20 UTC, merged