fix: create new useUrlSearchParams custom hook
virtool/virtool-ui pull request #269
Opened 2023-09-28 20:21 UTC by raastinn

2023-09-29 17:44 UTC, ReeceHoffmann requested changes

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/subtraction/components/Toolbar.jsx
> +        dispatch(findSubtractions(term));
Does this always work correctly without specifying the page?

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/utils/hooks.js
> +    if (window.location.search) {
Wouldn't you still want to set params even if `window.location.search` is empty? Also is this check required? URLSearchParams can probably handle either situation

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/subtraction/components/Toolbar.jsx
> +export const SubtractionToolbar = ({ onFind, canModify }) => {
docstring

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/subtraction/components/List.jsx
> +export function SubtractionList({ onLoadNextPage, documents, page, page_count, total_count, fetched }) {
docstring + typing for function signature.

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/subtraction/components/__tests__/Toolbar.test.jsx
>      });
All these component tests need to be updated to use RTL

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/utils/hooks.js
> +        window.history.replaceState({}, "", newUrl);
Is this the default history object? We use a streamlining library that acts as a shim over top of the built in history API to make it easier to work with for react-router. Would make for a cleaner call here as well https://github.com/remix-run/history/tree/v4/docs.

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/utils/hooks.js
> +    const [value, setValue] = useState(defaultValue);
I think you can remove this usage of state. Get the value from the URL which removes the possibility of desync. should also simplify the rest of the hook

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/utils/hooks.js
> +    const setUrlValue = newValues => {
nitpick:
```suggestion
    }, [key, defaultValue]);
    
    const setUrlValue = newValues => {
```

2023-09-29 17:44 UTC, ReeceHoffmann commented on src/js/utils/hooks.js
> +export function useUrlSearchParams({ key, defaultValue = "" }) {
docstring

2023-10-06 20:58 UTC, igboyes approved these changes

2023-10-11 18:41 UTC, igboyes requested changes
* Please update the files you touched to use TS and use `function` declarations.
* The naming in hooks is confused and inconsistent. Pay close attention to consistency and meaning in your names.

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +export function getUrlSearchParams(key) {
* Is this used anywhere else than line 66 of this module? If not, no need to export. Further, I don't think a separate function is much benefit.
* The naming is not good. It doesn't get params, it gets a search term.

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +}
The `newUrl` variable is not actually a URL. It is a URL path. You can avoid the naming issue by just doing.
```suggestion
export function updateUrlSearchParams(newTerm, key) {
    const search = new URLSearchParams(window.location.search);
    search.set(key, newTerm);
    window.history.replaceState({}, "", `${window.location.pathname}?${search.toString()}`);
}
```

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +    const search = new URLSearchParams(window.location.search);
You use `params` as the name for an object of the same type in the above function. Be consistent. I'd go with `params` as `search` implies action.

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +export function updateUrlSearchParams(newTerm, key) {
You write this generically for setting any search parameter, but it uses variable naming specific to the `term` use case.

```suggestion
export function updateUrlSearchParams(value, key) {
```

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +    const setUrlValue = newValue => {
* Use `function`.
* Why call this `setUrlValue`, then return it as `setValue`?

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> +    const searchTerm = getUrlSearchParams(key);
This is a generic hook for managing any search parameter. Why are you using the word 'term'?

2023-10-11 18:41 UTC, igboyes commented on src/js/utils/hooks.js
> + * @param defaultValue - The default value to use when the search parameter is not present in the URL
```suggestion
 * @param defaultValue - The default value to use when the search parameter key is not present in the URL
```

2023-10-11 23:22 UTC, raastinn commented
- After testing this again, I realised that the `setValue` served no purpose. With my previous code, if you refreshed on a filtered page, it didn't allow you to edit the text in the toolbar. This version fixes that and works as intended, using `useState` in Toolbar.jsx. 
- I only converted the `hooks.js` file to a TS file, as another issue already requires me converting the touched Subtraction files to TS.

2023-10-12 18:14 UTC, igboyes requested changes

2023-10-12 18:14 UTC, igboyes commented on src/js/utils/hooks.ts
> +        if (!searchValue && defaultValue) {
Why is there a naming difference between `searchValue` in this hook and `value` in `updateUrlSearchParams()`?

2023-10-12 18:14 UTC, igboyes commented on src/js/utils/hooks.ts
> +        value: searchValue || defaultValue,
There is a potential bug here. Think about what values `searchValue` could have.

2023-10-13 15:48 UTC, ReeceHoffmann commented
> * After testing this again, I realised that the `setValue` served no purpose.

There are two concerns I have with this change:

1. It removes the ability for the hook to be able to write the URLSearchParams, reducing its usefulness. (Think about cases where your using react-query instead of a prebuilt saga and need to update the URL)

2. When passing defaultValues they no longer will get written to the URL. As a result the default value being returned does not reflect the actual URL search params. 

Happy to talk these over if you want.

2023-10-13 16:04 UTC, raastinn commented
That makes more sense. I did some testing to see how it'll be once Redux is removed and you were right. Added it back

2023-10-13 16:14 UTC, ReeceHoffmann requested changes
Looking pretty good, mostly styling nitpicks

2023-10-13 16:14 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +export function useUrlSearchParams({ key, defaultValue }) {
Needs typing

2023-10-13 16:14 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +        value: value || defaultValue,
To extend Ian's comment, what happens if the `value` is `falsy` (ex: `""`) but correct.

2023-10-13 16:14 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +        value: value || defaultValue,
Nitpick: I would use an array instead of an object. Since the calling function should always want values and will often want `setValue` using an array allows for nicer renaming syntax on destructure with little drawback much like how `react` implements `useState`

2023-10-13 16:14 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +export function useUrlSearchParams({ key, defaultValue }) {
Nitpick: I would use positional arguments here. Using an object is more cumbersome and doesn't obviously provide a benefit here

2023-10-13 16:14 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +function updateUrlSearchParams(value, key) {
types + docstring

2023-10-20 16:40 UTC, ReeceHoffmann requested changes

2023-10-20 16:40 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +    const refValue = useRef(params.get(key) || defaultValue);
This still leaves open the possibility of desync between the URL and the state reported back. Imagine the case that the hook is called in two places, one to write (ex. toolbar) and one to read (ex. list view).

2023-10-26 18:49 UTC, ReeceHoffmann requested changes
Few small tweaks and I think this is ready to merge

2023-10-26 18:49 UTC, ReeceHoffmann commented on src/js/subtraction/components/List.jsx
> +    const [value] = useUrlSearchParams("find");
```suggestion
    const [term] = useUrlSearchParams("find");
```
More descriptive

2023-10-26 18:49 UTC, ReeceHoffmann commented on src/js/subtraction/components/Toolbar.jsx
> +    const [term, setTerm] = useState(value);
I don't think you need this since the term is stored in the URL. Removing should reduce opportunity for desync between the URL and searchbar

2023-10-26 18:49 UTC, ReeceHoffmann commented on src/js/subtraction/components/Toolbar.jsx
> +    const [value, setValue] = useUrlSearchParams("find");
```suggestion
    const [term, setTerm] = useUrlSearchParams("find");
```
more descriptive imo

2023-11-02 18:45 UTC, ReeceHoffmann approved these changes

2023-11-02 18:48 UTC, merged