refactor: add pagination to samples list view
virtool/virtool-ui pull request #283
Opened 2023-11-07 19:54 UTC by raastinn

2023-11-08 23:22 UTC, ReeceHoffmann requested changes
Good start. A lot of the components currently feel a bit complex. I think a good chunk of the logic can be simplified. Take another run through and see what you can do. `SampleList` and `quickAnalyze` and `ManageLabels` would especially benefit from some extra attention.

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +    return false;
The return value of this function seems overloaded to me. A single return value should stick to either determining the mode or whether to show the modal. Also not sure if this totally makes sense as a hook, guessing it could be paired down quite a bit.

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +    const mutation = useMutation(analyze);
Are there any queries that need to update on a successful analysis creation?

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +        return Array.from(new Set(referenceIds));
lodash: `uniq(By)` https://lodash.com/docs/4.17.15#uniqBy

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +    const { data: hasHmm } = useFindHmms();
Naming here wonky. `hasVar` namin scheme implies a bool, this is an object... also what about the case where the query has not yet resolved?

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/hmm/querys.ts
> +    return useQuery("hmms", findHmms);
Typing

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/hmm/querys.ts
> +}
Should be in `api` file

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/indexes/querys.ts
> +    return useQuery("listReadyIndex", listReadyIndexes);
typing

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/indexes/querys.ts
> +}
api file

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/Filter/LabelFilter.jsx
> +            : null;
1. Why not just use `isLoading`
2. How does this look when with higher latency on a fresh load? I have this sneaking suspicion that the labels popping in after the rest of the page loads might look a bit janky. might need to preload labels with the rest of the list

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +    const URLPage = parseInt(new URLSearchParams(location.search).get("page")) || 1;
Why not use the SearchParams hook for getting and setting page?

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +    const { documents, page, page_count, total_count } = data;
```suggestion
    }
    
    const { documents, page, page_count, total_count } = data;
```

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +    const { data, isLoading } = useFindSamples(URLPage, 4, term);
```suggestion
    const { data: samples, isLoading } = useFindSamples(URLPage, 4, term);
```

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +    }
Nitpick: simple enough I would define as an anon attached to the component using it

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +                document={document}
Redefine `SampleItem` as taking a sample as part of it's props. Way simpler interface

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +                select={select}
These two seem too similar, might just be a naming problem though

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +            }
xor?

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +            }
union?

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +                index={document.id}
destructure seems duplicate with all the explicit defns

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesToolbar.tsx
> +    },
I don't think this is even used...

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/components/Sidebar/ManageLabels.jsx
> +    const { data: allLabels, isLoading } = useFetchLabels();
```suggestion
    const { data: labels, isLoading } = useFetchLabels();
```

2023-11-08 23:22 UTC, ReeceHoffmann commented on src/js/samples/querys.ts
> +};
Not a query. Should be tweaking the custom hook to permit array values

2023-11-08 23:29 UTC, raastinn commented on src/js/samples/components/SamplesToolbar.tsx
> +    },
Yeah this was there before. Wasnn't sure if you still needed it so I just left it. I'll take it down

2023-11-10 20:50 UTC, raastinn commented on src/js/analyses/components/Create/Quick.jsx
> +    const mutation = useMutation(analyze);
If you're referring to `samplesQueryKeys.lists()` getting updated, I believe the changes in `websockets.ts` updates the status of the analyses in the sample item

2023-11-16 19:27 UTC, raastinn commented
![Screenshot from 2023-11-16 11-26-15](https://github.com/virtool/virtool-ui/assets/125520621/9e321b20-561f-4c8d-839c-f9841e04f326)
_Used 8 per page for screenshot_

2023-11-17 19:17 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +    const mutation = useMutation(analyze);
Is is updating automatically for you? In my local instance there is no samples WS message sent

2023-11-20 17:43 UTC, ReeceHoffmann requested changes
Mostly small stuff
 re query naming: I am thinking for consistency sake getting a list of anything should be `useListX` whereas getting single should be `useFetchX`. Open to other ideas as well

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +    function referenceId(selectedIndexes) {
nitpick: function is named like a variable

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/Quick.jsx
> +export function QuickAnalyze({ samples, subtractionOptions, onShortlistSubtractions, onClear }) {
Typing/docstrings generally missing from this module

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/hmm/querys.ts
> + */
`@returns`

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/indexes/api.ts
>  }
Is this used anywhere else?

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/indexes/querys.ts
> + */
`@returns`

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/samples/components/Filter/LabelFilter.tsx
> +            {Array.isArray(labels)
You need this check? typing as written suggest it should never be needed

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/indexes/querys.ts
> +}
Should be a general index fetching function that takes query params

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/samples/querys.ts
> +}
api.ts

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/js/utils/hooks.ts
> +        value.forEach(val => updateUrlSearchParamsList(val, key, history));
Why not just pass the whole array? Seems like it would simplify the logic quite a bit and be faster

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/tests/fake/sample.tsx
> +export function mockCreateSample() {
Does the name match what is being mocked?

2023-11-20 17:43 UTC, ReeceHoffmann commented on src/tests/fake/sample.tsx
> +                },
Mocked documents should specified when calling. Look at the other mock functions for examples

2023-12-04 18:44 UTC, ReeceHoffmann requested changes
Overall I think this is a step in the right direction for the codebase. I have two general things I want improved, but they may be more suited to another PR as I suspect they are holdovers from previous implementations:

1. When collecting a list of something (EX. SelectedSamples) I generally prefer to store the ids, then use those ids to lookup the original when needed. Prevents needing to write strange updaters

2. A lot of the logic surrounding labels is pretty tough to grok (EX: useUrlSearchParamsList and `getSelectedLabels`). I think it is a multifaceted typing/logic problem.

Take a look to see if you easily clean these up a bit, otherwise I think it is reasonable to fix these in another PR.

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/QuickAnalyze.tsx
> +                            </QuickAnalyzeError>{" "}
```suggestion
                            </QuickAnalyzeError>
```
Unless it is doing something

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/api.ts
> +    }
Do these need to be separate? I think superagent supports being passed an array of values, and undefined parameters should be ignored.

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +        );
Why store the whole sample instead of just the samples id? Save having to write updaters like this. Should also let you simplify other logic working with the list

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesList.tsx
> +                                : setFilterLabels(without(filterLabels, e.toString()));
Is `xor` an option here?

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/components/SamplesToolbar.tsx
> +    }
Looks like this is only used by `SampleSelectionToolbar` would define it there instead

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/components/__tests__/SamplesList.test.tsx
> +    const samples = [createFakeSampleMinimal(), createFakeSampleMinimal()];
Careful with this. All tests will share the same variables when running the test suite. This can result in subtle bugs where running as a single test it works but when they are run in a group tests start to fail since the previous tests modified the shared variables. 

Even though deepsource will complain, i generally would just initialise with no value and assign in `beforeEach` to eliminate this problem

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/querys.ts
> +    const workflows = params.get("workflows");
Should probably be passed as a regular param

2023-12-04 18:44 UTC, ReeceHoffmann commented on src/js/samples/querys.ts
> +            const allLabeled = selectedLabels.every(item => item.allLabeled === true);
If `SelectedLabels` is supposed to be `Labels[]` then where is `item.allLabeled` coming from. Somethings funky here.

2023-12-08 22:44 UTC, ReeceHoffmann requested changes

2023-12-08 22:44 UTC, ReeceHoffmann commented on src/js/analyses/components/Create/QuickAnalyze.tsx
> +    if (history.location.state?.["quickAnalysis"] === true) {
```suggestion
    if (history.location.state?.quickAnalysis === true) {
```
?

2023-12-08 22:44 UTC, ReeceHoffmann commented on src/js/samples/components/Filter/SampleFilters.tsx
> +type LabelFilterProps = {
```suggestion
type SampleFilterProps = {
```

2023-12-08 22:44 UTC, ReeceHoffmann commented on src/js/samples/querys.ts
> +};
```suggestion
type SampleLabel =Label & {
    allLabeled: boolean;
};
```
My suggested name isn't amazing, but makes a bit more clear it is not a standard label.

2023-12-11 16:39 UTC, ReeceHoffmann approved these changes

2023-12-11 16:48 UTC, ReeceHoffmann requested changes
Noticed bugs in manual testing after initial review:

1. Label filtering doesn't work
2. We are getting multistage loading of the main page

2023-12-12 21:41 UTC, ReeceHoffmann approved these changes, later dismissed

2023-12-12 21:42 UTC, ReeceHoffmann commented
Resolve the conflicts and I am good to merge

2023-12-12 22:09 UTC, ReeceHoffmann approved these changes

2023-12-12 22:13 UTC, merged