fix: excessive space in user creation dialog
virtool/virtool-ui pull request #297
Opened 2023-12-15 20:45 UTC by raastinn

2023-12-21 19:54 UTC, ReeceHoffmann requested changes

2023-12-21 19:54 UTC, ReeceHoffmann commented on src/js/users/components/CreateUser.tsx
> +            history.push({ state: { createUser: false } });
Hmm why the change here? I feel like the use of replace state may have been deliberate to prevent having the modal on the history stack

2023-12-21 19:54 UTC, ReeceHoffmann commented on src/js/users/components/ManageUsers.tsx
> +    const history = useHistory<{ createUser: boolean }>();
I think this still makes more sense as part of `CreateUser`. The strange desync issue experienced in testing seems worth confronting now, imo as we will likely have to deal with this down the road. If you haven't already, take some time to confirm the source of the problem and hunt for some other solutions. From my reading we should be using `MemoryRouter` more than we are in testing so we need to figure this out anyway.

2024-01-04 00:02 UTC, ReeceHoffmann commented
Given that `reach` seems to be the cause of our test flake issues I am proposing we close and start fresh with a new issue that just cleans up the look of the current modal rather than reverting to the old one. Happy to leave open if you think this is an easier starting point than fresh

2024-01-04 16:26 UTC, closed without merging

2024-01-15 20:39 UTC, igboyes commented
@ReeceHoffmann @raastinn Is this being addressed?