chore: update subtractions edit modal
virtool/virtool-ui pull request #304
Opened 2023-12-27 20:29 UTC by raastinn

2024-01-02 21:36 UTC, ReeceHoffmann requested changes
Changes so far look good. Might be a couple more things you can do. Not sure if react-query is in the cards here, might need to be done with the main component

2024-01-02 21:36 UTC, ReeceHoffmann commented on src/js/subtraction/components/Detail/__tests__/__snapshots__/EditSubtraction.test.tsx.snap
> +    onSubmit={[Function]}
Are these being used? looks like you did an RTL conversion for `EditSubtracton.test.tsx` so guessing these are vestigial

2024-01-02 21:36 UTC, ReeceHoffmann commented on src/js/subtraction/components/Detail/EditSubtraction.tsx
> +            dispatch(editSubtraction(id, name, nickname));
No luck with the websockets?

2024-01-02 21:36 UTC, ReeceHoffmann commented on src/js/subtraction/components/Detail/EditSubtraction.tsx
> +            </form>
The scope of this PR is fairly small so I think it is fair here to convert this over to react-hook-form

2024-01-02 22:34 UTC, raastinn commented on src/js/subtraction/components/Detail/EditSubtraction.tsx
> +            dispatch(editSubtraction(id, name, nickname));
Unfortunately not

2024-01-03 23:56 UTC, ReeceHoffmann approved these changes

2024-01-03 23:57 UTC, merged