chore: modernise subtractions detail view
virtool/virtool-ui pull request #309
Opened 2024-01-05 20:36 UTC by raastinn

2024-01-11 19:27 UTC, ReeceHoffmann requested changes

2024-01-11 19:27 UTC, ReeceHoffmann commented on src/js/subtraction/querys.ts
> +                }
I think It might actually make more sense to bump this into the queryClient definition in `app/App`. 
I can't see a broad benefit to re-trying requests that got 404'ed

2024-01-11 19:27 UTC, ReeceHoffmann commented on src/js/subtraction/reducer.js
>          })
Do either of these do anything if we aren't populating the main list of subtractions?

2024-01-11 19:27 UTC, ReeceHoffmann commented on src/js/subtraction/reducer.js
>      detail: null,
This can probably be cut way down

2024-01-11 19:27 UTC, ReeceHoffmann commented on src/js/subtraction/reducer.js
>              state.shortlist = action.payload;
How many components are still using the redux implementation of the subtraction shortlist at this point? Can we fully remove this if sample creation is merger first?

2024-01-11 19:27 UTC, ReeceHoffmann commented on src/js/subtraction/components/__tests__/Subtraction.test.tsx
> +        history.push(`/subtractions/${subtraction.id}`);
Not a change you made, but looks like the same history object is being used in every test in this module which is bad from a test isolation perspective. A new history object should be made before every test via `beforeEach`

2024-01-15 22:16 UTC, raastinn commented on src/js/subtraction/reducer.js
>              state.shortlist = action.payload;
`CreateAnalysis`, `QuickAnalyze`, and `SampleDetail` are still using subtraction shortlist

2024-01-17 21:33 UTC, ReeceHoffmann approved these changes

2024-01-17 21:33 UTC, merged