chore: rework`EmptyReference` to use react-hook-form
virtool/virtool-ui pull request #310
Opened 2024-01-08 23:24 UTC by raastinn

2024-01-11 17:20 UTC, ReeceHoffmann requested changes
Code looks overall really close to what we want. Keep a close eye out for styling changes and consider if they both look better and/or provide a better user experience than the previous version.

2024-01-11 17:20 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +    mode: string;
Should be an enum dictating what the valid states are. Look for usages and create an enum around expected values

2024-01-11 17:20 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +                <InputSimple as="textarea" id="organism" {...register("organism")} />
Why the change from a regular input to a textarea?

2024-01-11 17:20 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +                <InputSimple as="textarea" id="description" {...register("description")} />
Why are you using passing `textarea` vs simply using `TextArea`? This will apply the styles from `InputSimple` which may not be what you want when creating a larger text input

2024-01-11 17:20 UTC, ReeceHoffmann commented on src/js/references/components/__tests__/EmptyReference.test.tsx
> +    });
Looks like a dupe of an above test

2024-01-11 17:20 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +import { FormValues } from "./EmptyReference";
imo it is a bit weird for `FormValues` to be defined outside of the actual form module. Esp when `ReferenceForm` is used by other components

2024-01-17 21:44 UTC, ReeceHoffmann requested changes
Small stuff. Would be nice to clean up the API `TextArea`. Okay to merge either way on the `Mode` comments

2024-01-17 21:44 UTC, ReeceHoffmann commented on src/js/base/TextArea.tsx
> +    return <StyledTextArea as="textarea" {...(register && register(name))} {...props} />;
This because of `ref`? `React.forwardRef` might be a cleaner soln here

2024-01-17 21:44 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +export enum Mode {
Will this name make sense in the importing component?

2024-01-17 21:44 UTC, ReeceHoffmann commented on src/js/references/components/ReferenceForm.tsx
> +    if (mode === "empty" || mode === "edit") {
Since your defining an enum you can do the comparison with the enum rather than the raw string

2024-01-19 00:32 UTC, raastinn commented
Updated `TextArea` to use `React.forwardRef` rather than the method before. Imo the previous one looks more cleaned up, let me know what you think.

2024-01-22 22:22 UTC, ReeceHoffmann approved these changes

2024-01-22 22:23 UTC, merged