chore: Rework `OTUGeneral` to use react-query
virtool/virtool-ui pull request #380
Opened 2024-03-06 20:32 UTC by raastinn

2024-03-08 00:13 UTC, ReeceHoffmann requested changes

2024-03-08 00:13 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/OTUDetail.tsx
> +
docstring

2024-03-08 00:13 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/OTUDetail.tsx
> +export function OTUDetail(props) {
Destructure props. 

Also consider adding typing. Might not make sense to spend much time on complex typing for redux code that we are going to bail on. Not blocking, will merge without typing.

2024-03-08 00:13 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/OTUDetail.tsx
> +    let modifyOTUComponents;
bump this closer to usage. (next to `IconButtons)

2024-03-08 00:13 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/OTUDetail.tsx
> +            </>
Would this make sense as it's own component? Could factor out perms checking with the buttons as well

2024-03-08 00:13 UTC, ReeceHoffmann commented on src/js/otus/types.ts
> -    issues?: { [key: string]: any } | boolean;
Sadly the old typing is correct and the UI needs to be able to handle it atm:

https://github.com/virtool/virtool-core/blob/d4acce2e9c1fe5c6b9421854702bb1911b746d1a/virtool_core/models/otu.py

2024-03-08 19:39 UTC, raastinn commented on src/js/otus/components/Detail/OTUDetail.tsx
> +export function OTUDetail(props) {
Done. I think i'll save the typing for the conversion issue.

2024-03-11 16:53 UTC, ReeceHoffmann commented on src/js/base/IconLink.tsx
> +            <Icon as="button" color={color} name={name} tip={tip} hoverable />
Why the switch up here? The icon has no inherent functionality here, so I my instinct here is that it is semantically incorrect to render it as a button. If your going for a look it is probably best to take advantage of classname and apply additional styles

2024-03-11 19:08 UTC, raastinn commented
![Screenshot from 2024-03-11 12-03-18](https://github.com/virtool/virtool-ui/assets/125520621/f830bcbc-b4d2-429b-a0bc-0bd1e05a004d)

2024-03-11 22:20 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/OTUHeaderEndIcons.tsx
> +const RemoveOTUIcon = styled(IconLink)`
Nitpick: I would just have a single `OTUIcon` since the style changes your applying are identical

2024-03-12 15:55 UTC, ReeceHoffmann approved these changes

2024-03-12 15:56 UTC, merged