chore: Update components in `Schema` directory to use react-query
virtool/virtool-ui pull request #388
Opened 2024-03-15 22:32 UTC by raastinn

![Screenshot from 2024-03-15 15-31-37](https://github.com/virtool/virtool-ui/assets/125520621/06b3d3db-4c70-47a4-885f-4f091c463ec7)

![Screenshot from 2024-03-15 15-15-46](https://github.com/virtool/virtool-ui/assets/125520621/876f6c8c-d690-4ab4-9e05-d74cc5bb2ce1)

Also made styling changes to adhere to the new styling we are using.

2024-03-22 22:20 UTC, ReeceHoffmann requested changes

2024-03-22 22:20 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/EditOTU.tsx
> +        <Dialog open={location.state?.editOTU} onOpenChange={onHide}>
Does changing history in `onOpenChange` do anything? Seems like it would be called after history has already been changed

2024-03-22 22:20 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/Schema/AddSegment.tsx
> +            setError("Segment names must be unique. This name is currently in use.");
Can this be integrated more naturally with the forms validation?

2024-03-22 22:20 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/Schema/EditSegment.tsx
> +            newArray[index] = { name: segmentName, molecule, required };
`map` ?

2024-03-22 22:20 UTC, ReeceHoffmann commented on src/js/otus/types.ts
> +    schema: Array<OTUSegment>;
is this correct?

2024-03-25 19:06 UTC, raastinn commented on src/js/otus/components/Detail/EditOTU.tsx
> +        <Dialog open={location.state?.editOTU} onOpenChange={onHide}>
Kept this since without it the dialog wont close

2024-03-26 21:11 UTC, ReeceHoffmann approved these changes

2024-03-26 21:12 UTC, merged