refactor: remove `react-beautiful-dnd` & reorder schema list with arrows
virtool/virtool-ui pull request #403
Opened 2024-04-02 22:42 UTC by raastinn

![Screenshot from 2024-04-02 15-37-46](https://github.com/virtool/virtool-ui/assets/125520621/fff0d01b-62f8-4309-b6f2-d27ef97b715b)
![Screenshot from 2024-04-02 15-38-18](https://github.com/virtool/virtool-ui/assets/125520621/e0c5401e-6487-43f6-9905-23ffb88bdd52)

**_Note:_** removed alphabetical sorting of the schema's using `sortBy` since it messes up with the index order

2024-04-05 23:01 UTC, ReeceHoffmann requested changes
Visually I would make the carets bigger, right now they are too small to make for nice buttons. I would also consider stacking them vertically with a bit of space between them

2024-04-05 23:01 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/Schema/Schema.tsx
> +        updatedSchema[index - 1] = temp;
nitpick: I like the shorter es6 syntax,  both are fine though tbh
```suggestion
        const updatedSchema = data.schema.slice();
        [updatedSchema[index], updatedSchema[index-1]] = [updatedSchema[index-1], updatedSchema[index]] 
```

2024-04-05 23:01 UTC, ReeceHoffmann commented on src/js/otus/components/Detail/Schema/Schema.tsx
> +            { otuId, name, abbreviation, schema: updatedSchema },
Can you get away with updating only the schema?

Also worth considering factoring the mutation out rather then duplicating it

2024-04-08 19:47 UTC, raastinn commented
![Screenshot from 2024-04-08 12-46-42](https://github.com/virtool/virtool-ui/assets/125520621/b821181f-c826-4570-842a-8acb4285d6cd)

2024-04-16 20:16 UTC, ReeceHoffmann commented
Style review round 2:
 - At least double the actual icon size, they should be a comfortable size to quickly click
 - The area between the icons should not be clickable, active area should be the icon itself or a tight square around the icon
 - Should probably have a hover color to match the style of other buttons in the UI
 - consider offsetting the icons for the top and bottom item so they are in the same position they otherwise would be in

2024-04-22 23:19 UTC, raastinn commented
![Screenshot from 2024-04-22 16-16-30](https://github.com/virtool/virtool-ui/assets/125520621/611e817b-e3f0-4da6-aaa6-955418804ef7)

2024-04-22 23:40 UTC, igboyes commented
I think the side-by-side design was better.

The carets now look too similar to graphics that would normally indicate the elements can be reordered vertically by drag-drop.

That the first and last elements only have one icon is less obvious when they are closely stacked in a vertical line. Horizontally, it is obvious, and a good clue to the user for how the interface works.

2024-04-23 18:57 UTC, raastinn commented
![Screenshot from 2024-04-23 11-56-31](https://github.com/virtool/virtool-ui/assets/125520621/eebb4c93-938e-4aa1-95a5-9ac582cd97f6)

2024-04-24 21:51 UTC, ReeceHoffmann commented
I am happy with this version. @igboyes?

2024-04-24 22:08 UTC, igboyes commented
@raastinn @ReeceHoffmann Needs conflicts resolved, then you should merge

2024-04-25 14:57 UTC, merged