chore: rework components in jobs category to use react query
virtool/virtool-ui pull request #412
Opened 2024-04-15 20:57 UTC by raastinn

2024-04-15 22:38 UTC, ReeceHoffmann requested changes

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/__tests__/JobSteps.test.tsx
> +                { state: "running" as JobState, timestamp: "2024-04-12T21:50:19.108000Z", progress: 40 },
```suggestion
                { state: JobState.waiting, timestamp: "2024-04-12T21:50:19.108000Z", progress: 40 },
                { state: "running" as JobState, timestamp: "2024-04-12T21:50:19.108000Z", progress: 40 },
```
?

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/app/websocket/reactQueryHandler.ts
> +        queryClient.invalidateQueries(jobQueryKeys.lists());
Aren't all the job key's getting invalidated already?

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/api.ts
> +export const get = ({ jobId }) => Request.get(`/jobs/${jobId}`);
This still getting used?

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/Filters/JobFilters.tsx
> +};
Should be part of `types.ts`

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/Filters/StateCategory.tsx
> +    states: { [key: string]: any };
Can you get more specific than this? As written this type is not helpful imo

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/Filters/StateFilter.tsx
> +    };
`counts` typing should be defined in `types.ts` since it is part of the jobs response

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/Filters/StateFilter.tsx
> +    const count = mapValues(counts, workflowCounts => reduce(workflowCounts, (result, value) => (result += value), 0));
misleading naming

2024-04-15 22:38 UTC, ReeceHoffmann commented on src/js/jobs/components/JobDetail.tsx
> +    let color: "blue" | "green" | "red" | "orange" | "purple" = "green";
Is it ever orange or purple?

2024-04-18 22:10 UTC, raastinn commented on src/js/jobs/components/__tests__/JobSteps.test.tsx
> +                { state: "running" as JobState, timestamp: "2024-04-12T21:50:19.108000Z", progress: 40 },
Currently `JobState` is a type not an enum, turning into one we would have to slightly rework the typing of all components that use it. I figured to leave it to a following issue so that it can be more clear to work through if that's okay with you.

2024-04-19 15:48 UTC, ReeceHoffmann approved these changes

2024-04-19 15:51 UTC, merged