refactor: rework samples sidebar directory to use typescript
virtool/virtool-ui pull request #416
Opened 2024-04-17 22:18 UTC by raastinn

## Changes

## Compatiblity

Any changes that require a newer version of the API are considered breaking
changes.

Common breaking changes:
 - Making a request to a new API endpoint that will return `403` or `404` in older versions of the API.
 - No longer sending request fields required by previous versions of the API 
 - Requiring new fields from an API endpoint that will not be present in
   responses from older versions of the API
 - Breaking backwards compatibility with old response data shapes

Choose one:
 - [x] The changes do not break compatibility
 - [ ] The changes potentially break compatibility

## Pre-Review Checklist
 - [X] All changes are tested
 - [X] All touched code documentation is updated
 - [x] All tests pass in your local environment
 - [x] Deepsource issues have been reviewed and addressed
 - [X] Debugging logging and commented out code has been removed

 
## Screenshots:
_Only required for visual changes_.

2024-04-19 16:19 UTC, ReeceHoffmann commented on src/js/samples/components/Sidebar/SampleSidebarSelector.tsx
> +                selected={selectedItems.includes(id as never)}
Hmm why the usage of `never`? Either the check or typing doesn't make much sense here

2024-05-02 16:09 UTC, ReeceHoffmann commented
Current status? tsc check is still looks like it is having problems

2024-05-10 15:08 UTC, ReeceHoffmann requested changes

2024-05-10 15:08 UTC, ReeceHoffmann commented on src/js/samples/components/Create/CreateSample.tsx
> +                    setFieldValue: (field: string, value: string | string[] | number[]) => void;
```suggestion
                    setFieldValue: (field: string, value:  string[] | number[]) => void;
```
Why allow a single string on it's own?

2024-05-10 15:08 UTC, ReeceHoffmann commented on src/js/samples/components/Sidebar/SampleSidebarSelector.tsx
> +                    : (selectedItems as string[]).includes(item.id as string)
I would give this a rework using generics. You should be able to declare a type such that is either a string or number but only one of the two. As written this introduces an`if` into the runtime,  while the types are removed at compile time.

2024-05-10 21:55 UTC, raastinn commented on src/js/samples/components/Create/CreateSample.tsx
> +                    setFieldValue: (field: string, value: string | string[] | number[]) => void;
Some of the other form values like `group` use strings

2024-05-13 22:19 UTC, ReeceHoffmann approved these changes

2024-05-13 22:19 UTC, merged