refactor: rework create sample to use react hook form
virtool/virtool-ui pull request #479
Opened 2024-07-02 22:33 UTC by raastinn

## Changes

## Compatiblity

Any changes that require a newer version of the API are considered breaking
changes.

Common breaking changes:
 - Making a request to a new API endpoint that will return `403` or `404` in older versions of the API.
 - No longer sending request fields required by previous versions of the API 
 - Requiring new fields from an API endpoint that will not be present in
   responses from older versions of the API
 - Breaking backwards compatibility with old response data shapes

Choose one:
 - [ ] The changes do not break compatibility
 - [ ] The changes potentially break compatibility

## Pre-Review Checklist
 - [ ] All changes are tested
 - [ ] All touched code documentation is updated
 - [ ] All tests pass in your local environment
 - [ ] Deepsource issues have been reviewed and addressed
 - [ ] Debugging logging and commented out code has been removed

 
## Screenshots:
_Only required for visual changes_.

2024-07-09 14:39 UTC, ReeceHoffmann requested changes

2024-07-09 14:39 UTC, ReeceHoffmann commented on src/js/samples/api.ts
> + * @param locale -
```suggestion
 * @param host - the name of the host species the virus was identified in
 * @param locale - the geographical location of the virus detection
```

2024-07-09 14:39 UTC, ReeceHoffmann commented on src/js/samples/components/Create/CreateSample.tsx
> +    } = usePersistentForm<FormValues>({
Are you handling the possibility of a sample file no longer being valid between loads somewhere?

2024-07-09 14:39 UTC, ReeceHoffmann commented on src/js/samples/components/Create/CreateSample.tsx
> +    }, [account]);
Why this instead of setting it as a `defaultValue`?

2024-07-09 14:39 UTC, ReeceHoffmann commented on src/tests/fake/samples.tsx
> +        .reply(200, sample);
Is this change based off what the API is currently returning? In theory the API should be returning 201, not sure if in practice it is though

2024-07-16 19:17 UTC, raastinn commented on src/js/samples/components/Create/CreateSample.tsx
> +    } = usePersistentForm<FormValues>({
Yeah the form deselects the file if it is deleted between loads.

2024-07-16 19:18 UTC, raastinn commented on src/js/samples/components/Create/CreateSample.tsx
> +    }, [account]);
Since we're setting it before we ensure that `Account` is finished loading, the default value would always just be null.

2024-07-17 21:47 UTC, merged