refactor: create subtraction file selector not accessible
virtool/virtool-ui pull request #522
Opened 2024-07-29 20:57 UTC by raastinn

## Changes
- Also uninstalled `redux` packages that got re-installed after removal

## Pre-Review Checklist
* [ ] I have considered backwards and forwards compatibility.
* [ ] All changes are tested.
* [ ] All touched code documentation is updated.
* [ ] All tests pass in my local environment
* [ ] Deepsource issues have been reviewed and addressed.
* [ ] Commented code and `console` usages have been removed.
 
## Screenshots
_Only required for visual changes_

2024-07-31 18:35 UTC, igboyes requested changes
I haven't checked this out locally, but I can't see how these changes would resolve the issue.

Maybe I should have been more specific. The selector cannot take focus through the keyboard. It is not accessible.

Try focusing on the **Name** field. Then, use the tab key to navigate through the accessible form elements. You will notice that the selector element and the file items within it cannot be focussed with tab.

Looks at `Select` or `ToggleGroup` in Radis for the behaviour we need (try tabbing through the examples). It is okay to completely change the component, like moving to a select box solution.

2024-08-01 18:34 UTC, raastinn commented
> I haven't checked this out locally, but I can't see how these changes would resolve the issue.
> 
> Maybe I should have been more specific. The selector cannot take focus through the keyboard. It is not accessible.
> 
> Try focusing on the **Name** field. Then, use the tab key to navigate through the accessible form elements. You will notice that the selector element and the file items within it cannot be focussed with tab.
> 
> Looks at `Select` or `ToggleGroup` in Radis for the behaviour we need (try tabbing through the examples). It is okay to completely change the component, like moving to a select box solution.

That makes more sense. My current solution is just working off the component we already have. If you think Radix would be better I can change to that.

2024-08-12 20:30 UTC, ReeceHoffmann commented
I checked the branch out and imo it does address the basic problem as described. I susepct assigning the `role=button` is what is making it work. The said would the `listbox` and `option` labels for the main list and each individual option make more sense?

Using Radix or Shadcn is also fine with me, none of the components are really drop-in though. Both the `combobox` and the `select` are really built around using a drop down menu. @raastinn If you haven't alreayd double check me on this.

Once we are happy that the aria-label is correct I am happy to merge and we can decide about conversion to a drop-down in another PR

2024-08-12 20:31 UTC, ReeceHoffmann commented on src/js/base/BoxGroupSectionSelect.tsx
> +        <SelectBoxGroupSection
nitpick
```suggestion
export function SelectBoxGroupSection({ active, children, className, onClick }: BoxGroupSectionSelectProps) {
    function handleKeyDown(e) {
        if (e.key === "Enter") {
            onClick();
        }
    }
    return (
        <StyledSelectBoxGroupSection
```

2024-08-23 15:10 UTC, ReeceHoffmann approved these changes

2024-08-23 15:14 UTC, merged