refactor: reimplement markdown base component in tailwind
virtool/virtool-ui pull request #526
Opened 2024-08-01 22:10 UTC by raastinn

## Pre-Review Checklist
* [ ] I have considered backwards and forwards compatibility.
* [ ] All changes are tested.
* [ ] All touched code documentation is updated.
* [ ] All tests pass in my local environment
* [ ] Deepsource issues have been reviewed and addressed.
* [ ] Commented code and `console` usages have been removed.
 
## Screenshots
_Only required for visual changes_

2024-08-01 22:33 UTC, igboyes requested changes
There is missing work here. Please re-read the issue.

2024-08-01 22:33 UTC, igboyes commented on src/js/base/Markdown.tsx
> + * A styled markdown component
There is much more to this component than that.

2024-08-01 23:28 UTC, raastinn commented
> There is missing work here. Please re-read the issue.

Sorry, didn't read it carefully. Reworked the issue to add it to storybook along with updating the testing and docstrings.

2024-08-19 17:54 UTC, ReeceHoffmann approved these changes

2024-08-19 17:55 UTC, merged